import getTrainerImage from './TrainerLevels';

const UpgradesParams = [
  {
    id: 1,
    title: "Подкачаться",
    img: "./src/assets/Trainer/img2.jpg",
    desc: "Когда ты весишь 150 сложно не платить тебе за персональные тренировки",
    maxLvlText: "Поздравляем! Теперь вы можете открывать свои залы",
    initialPrice: 150,
    initialIncrease: 1,
    isIncreaseMoney: true,
    images: getTrainerImage, 
    maxLvl: 20,
    isHidden: false,
    isInvisible: false,
    level: 0,
  },
  {
    id: 2,
    title: "реклама в соц сетях",
    img: "src/assets/Upgrades/upgrade2.jpeg",
    desc: "теперь о тебе будут знать не только бабушки из твоего подъезда",
    maxLvlText: "",
    initialPrice: 700,
    initialIncrease: 3,
    isIncreaseMoney: false,
    images: () => false,
    maxLvl: 20,
    isHidden: true,
    isInvisible: false,
    level: 0,
  },
  {
    id: 3,
    title: "купить рекламу",
    img: "src/assets/Upgrades/upgrade2.jpeg",
    desc: "Ты Привлекаешь новых клиентов через свой блог в соц сетях и получаешь дополниткльный доход",
    maxLvlText: "",
    initialPrice: 700,
    initialIncrease: 3,
    isIncreaseMoney: false,
    images: () => false,
    maxLvl: 7,
    isHidden: true,
    isInvisible: true,
    level: 0,
  },
  {
    id: 4,
    title: "купить рекламу",
    img: "src/assets/Upgrades/upgrade2.jpeg",
    desc: "Ты Привлекаешь новых клиентов через свой блог в соц сетях и получаешь дополниткльный доход",
    maxLvlText: "",
    initialPrice: 700,
    initialIncrease: 3,
    isIncreaseMoney: false,
    images: () => false,
    maxLvl: 7,
    isHidden: true,
    isInvisible: true,
    level: 0,
  },
  // other upgrades
];

export default UpgradesParams;